name: branch-push
run-name: ${{ github.REF_NAME }} pull request
on:
  push:
    branches:
      - "*"
      - "!master"

jobs:
  create-pr:
    runs-on: ${{ vars.UBUNTU_IMAGE }}
    steps:
      - name: Create PR
        uses: RedSockActions/create_pr@v0.0.10
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
