name: master-actions
run-name: RELEASE
on:
  push:
    branches:
      - master

jobs:
  registry_release:
    runs-on: ubuntu-latest
    steps:
      - name: Release image
        if: ${{ needs.tag-release.outputs.tag != '' }}
        uses: RedSockActions/release_image@v1.0.16
        with:
          REGISTRY_USER: ${{ vars.REGISTRY_USER }}
          REGISTRY_PWD: ${{ secrets.REGISTRY_PWD }}
